# Generated by Django 5.2.16 on 2026-07-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0011_ai_kind_suggest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
