# Generated by Django 5.2.16 on 2026-07-17 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0012_alter_collabmessage_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collabmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='collab.collabmessage', verbose_name='引用消息'),
        ),
        migrations.CreateModel(
            name='CollabSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_mode', models.CharField(choices=[('auto', '智能选取'), ('latest', '最近消息'), ('time', '时间范围'), ('custom', '自定义范围')], default='auto', max_length=16, verbose_name='选取方式')),
                ('message_count', models.PositiveIntegerField(default=0, verbose_name='纳入消息数')),
                ('selection_reason', models.CharField(blank=True, default='', max_length=240, verbose_name='选取说明')),
                ('content', models.TextField(blank=True, default='', verbose_name='总结正文')),
                ('key_points', models.JSONField(blank=True, default=list, verbose_name='关键要点')),
                ('decisions', models.JSONField(blank=True, default=list, verbose_name='结论/共识')),
                ('action_items', models.JSONField(blank=True, default=list, verbose_name='待办事项')),
                ('participants', models.JSONField(blank=True, default=list, verbose_name='发言成员')),
                ('generated_by', models.CharField(choices=[('llm', '模型'), ('local', '本地规则')], default='local', max_length=16, verbose_name='生成方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_summaries_created', to=settings.AUTH_USER_MODEL)),
                ('end_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collab.collabmessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='collab.collabroom')),
                ('start_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collab.collabmessage')),
            ],
            options={
                'verbose_name': '协作纪要',
                'verbose_name_plural': '协作纪要',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CollabMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency_ms', models.PositiveBigIntegerField(default=0, verbose_name='从发送到已读耗时(ms)')),
                ('read_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='collab.collabmessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reads', to='collab.collabroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_message_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '协作消息已读',
                'verbose_name_plural': '协作消息已读',
                'indexes': [models.Index(fields=['room', 'read_at'], name='collab_read_room_time')],
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='uniq_collab_message_reader')],
            },
        ),
        migrations.CreateModel(
            name='CollabReadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, verbose_name='前端会话标识')),
                ('up_to_message_id', models.BigIntegerField(default=0, verbose_name='阅读到消息ID')),
                ('active_duration_ms', models.PositiveBigIntegerField(default=0, verbose_name='活跃阅读时长(ms)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_sessions', to='collab.collabroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_read_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '协作阅读会话',
                'verbose_name_plural': '协作阅读会话',
                'indexes': [models.Index(fields=['room', 'last_active_at'], name='collab_session_room_time')],
                'constraints': [models.UniqueConstraint(fields=('room', 'user', 'session_key'), name='uniq_collab_read_session')],
            },
        ),
    ]
