# Generated by Django 5.2.16 on 2026-07-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0013_collabmessage_reply_to_collabsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabsummary',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='模型名称'),
        ),
        migrations.AddField(
            model_name='collabsummary',
            name='model_source',
            field=models.CharField(blank=True, choices=[('personal', '个人配置'), ('platform', '平台配置'), ('platform_fallback', '平台回退')], default='', max_length=24, verbose_name='模型配置来源'),
        ),
    ]
