# Generated by Django 5.2.16 on 2026-07-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0013_xiaoce_run_and_message_meta'),
        ('collab', '0014_collabsummary_model_name_collabsummary_model_source'),
    ]

    operations = [
    ]
