# Generated by Django 5.2.16 on 2026-07-22 03:21

import apps.loops.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_platform_team_creator_membership'),
        ('loops', '0001_initial'),
        ('ontology', '0002_ontrelation_causal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('days', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='model_definition', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(max_length=32)),
                ('equation', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(max_length=32)),
                ('parameters', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LoopVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('candidate', '候选'), ('confirmed', '已确认'), ('archived', '已归档')], default='candidate', max_length=16)),
                ('definition', models.JSONField(default=dict)),
                ('parameter_hash', models.CharField(max_length=80)),
                ('engine_version', models.CharField(default='inventory-balance-v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='MetricBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_key', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(default=apps.loops.models.new_simulation_key, max_length=96)),
                ('idempotency_key', models.CharField(max_length=96)),
                ('parameters', models.JSONField(default=dict)),
                ('input_hash', models.CharField(max_length=80)),
                ('result', models.JSONField(default=dict)),
                ('result_hash', models.CharField(max_length=80)),
                ('engine_version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('completed', '完成'), ('blocked', '阻断'), ('failed', '失败')], default='completed', max_length=16)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(max_length=32)),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedbackloop',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='loopmember',
            options={'ordering': ['sequence', 'id']},
        ),
        migrations.AddField(
            model_name='feedbackloop',
            name='causal_maturity',
            field=models.CharField(choices=[('hypothesis', '假设'), ('supported', '有证据支持'), ('validated', '已验证')], default='hypothesis', max_length=16),
        ),
        migrations.AddField(
            model_name='feedbackloop',
            name='confirmed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_loops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackloop',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackloop',
            name='current_version_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedbackloop',
            name='loop_key',
            field=models.CharField(default=apps.loops.models.new_loop_key, max_length=96, verbose_name='稳定回路标识'),
        ),
        migrations.AddField(
            model_name='feedbackloop',
            name='model_level',
            field=models.CharField(choices=[('L0', '定性解释'), ('L1', '启发式情景'), ('L2', '校准情景'), ('L3', '回测验证'), ('L4', '受控预测')], default='L0', max_length=2),
        ),
        migrations.AddField(
            model_name='feedbackloop',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_loops', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='feedbackloop',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='feedbackloop',
            name='confirmed_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='兼容确认人'),
        ),
        migrations.AlterField(
            model_name='loopmember',
            name='loop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='loops.feedbackloop'),
        ),
        migrations.AlterField(
            model_name='loopmember',
            name='note',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='loopmember',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop_memberships', to='ontology.ontrelation'),
        ),
        migrations.AlterField(
            model_name='loopmember',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='feedbackloop',
            constraint=models.UniqueConstraint(fields=('organization', 'loop_key'), name='uniq_org_loop_key'),
        ),
    ]
