# Generated by Django 5.2.16 on 2026-07-22 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_platform_team_creator_membership'),
        ('datalake', '0001_initial'),
        ('loops', '0002_delay_evidencebinding_flow_intervention_loopversion_and_more'),
        ('ontology', '0003_causallink_ontalias_ontassertion_ontevidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencebinding',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loop_bindings', to='ontology.ontevidence'),
        ),
        migrations.AddField(
            model_name='delay',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='loops.flow'),
        ),
        migrations.AddField(
            model_name='loopversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loopversion',
            name='loop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='loops.feedbackloop'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='loops.loopversion'),
        ),
        migrations.AddField(
            model_name='flow',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='loops.loopversion'),
        ),
        migrations.AddField(
            model_name='evidencebinding',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_bindings', to='loops.loopversion'),
        ),
        migrations.AddField(
            model_name='delay',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='loops.loopversion'),
        ),
        migrations.AddField(
            model_name='metricbinding',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loop_bindings', to='datalake.metriccontract'),
        ),
        migrations.AddField(
            model_name='metricbinding',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_bindings', to='loops.loopversion'),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='metric_results',
            field=models.ManyToManyField(related_name='simulation_runs', to='datalake.metricresult'),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='core.organization'),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_runs', to='datalake.sourcesnapshot'),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_runs', to='loops.loopversion'),
        ),
        migrations.AddField(
            model_name='stock',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='loops.loopversion'),
        ),
        migrations.AddField(
            model_name='flow',
            name='source_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='loops.stock'),
        ),
        migrations.AddField(
            model_name='flow',
            name='target_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inflows', to='loops.stock'),
        ),
        migrations.AddConstraint(
            model_name='loopversion',
            constraint=models.UniqueConstraint(fields=('loop', 'version'), name='uniq_loop_version'),
        ),
        migrations.AddConstraint(
            model_name='metricbinding',
            constraint=models.UniqueConstraint(fields=('version', 'variable_key'), name='uniq_version_metric_binding'),
        ),
        migrations.AddConstraint(
            model_name='simulationrun',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_org_sim_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('version', 'key'), name='uniq_version_stock_key'),
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(fields=('version', 'key'), name='uniq_version_flow_key'),
        ),
    ]
