# Generated by Django 5.2.16 on 2026-07-22 09:39

import apps.loops.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_platform_team_creator_membership'),
        ('loops', '0004_scope_legacy_loops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_key', models.CharField(default=apps.loops.models.new_ops_loop_key, max_length=96, verbose_name='稳定标识')),
                ('name', models.CharField(max_length=160, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('candidate', '候选'), ('active', '运行中'), ('paused', '暂停'), ('error', '异常'), ('archived', '已归档')], default='draft', max_length=16)),
                ('source', models.CharField(choices=[('ai', 'AI发现'), ('manual', '手动')], default='manual', max_length=16)),
                ('confidence', models.PositiveSmallIntegerField(default=0, verbose_name='置信度')),
                ('definition', models.JSONField(default=apps.loops.models.default_ooda_definition, verbose_name='OODA定义')),
                ('knowledge_refs', models.JSONField(blank=True, default=list, verbose_name='知识引用')),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict, verbose_name='指标快照')),
                ('ooda_phase', models.CharField(choices=[('observe', '观察'), ('orient', '理解'), ('decide', '决策'), ('act', '执行'), ('learn', '学习'), ('idle', '空闲')], default='idle', max_length=16)),
                ('last_result', models.JSONField(blank=True, default=dict, verbose_name='最近一轮结果')),
                ('current_run_key', models.CharField(blank=True, default='', max_length=96)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ops_loops', to=settings.AUTH_USER_MODEL)),
                ('linked_feedback_loop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_links', to='loops.feedbackloop')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_loops', to='core.organization')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OperationalLoopRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(default=apps.loops.models.new_ops_run_key, max_length=96)),
                ('round', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', '排队'), ('running', '运行中'), ('awaiting_confirm', '待确认'), ('completed', '完成'), ('failed', '失败')], default='pending', max_length=24)),
                ('phase', models.CharField(choices=[('observe', '观察'), ('orient', '理解'), ('decide', '决策'), ('act', '执行'), ('learn', '学习')], default='observe', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('trace_id', models.CharField(blank=True, default='', max_length=96)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('phase_results', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_loop_runs', to=settings.AUTH_USER_MODEL)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='loops.operationalloop')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_loop_runs', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='operationalloop',
            constraint=models.UniqueConstraint(fields=('organization', 'loop_key'), name='uniq_org_ops_loop_key'),
        ),
        migrations.AddConstraint(
            model_name='operationallooprun',
            constraint=models.UniqueConstraint(fields=('organization', 'run_key'), name='uniq_org_ops_run_key'),
        ),
    ]
