# Generated by Django 5.2.16 on 2026-07-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('brand', '品牌页'), ('shop', '店铺页'), ('sku', 'SKU页'), ('flow', '流程页'), ('system', '系统页'), ('metric', '指标页')], max_length=16, verbose_name='类型')),
                ('key', models.CharField(db_index=True, max_length=128, verbose_name='实体标识')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容(Markdown)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Wiki 页面',
                'verbose_name_plural': 'Wiki 页面',
                'ordering': ['kind', 'key'],
                'unique_together': {('kind', 'key')},
            },
        ),
    ]
