# Generated by Django 5.2.16 on 2026-07-08 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('emoji', models.CharField(default='🤖', max_length=8, verbose_name='头像 emoji')),
                ('role', models.CharField(blank=True, max_length=128, verbose_name='角色/人设')),
                ('expertise', models.CharField(blank=True, max_length=200, verbose_name='专长')),
                ('persona', models.TextField(blank=True, verbose_name='人设描述(系统提示)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '对象 Agent',
                'verbose_name_plural': '对象 Agent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='会议标题')),
                ('question', models.TextField(verbose_name='核心问题(全程围绕它)')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '已暂停'), ('stopped', '已结束')], default='active', max_length=16, verbose_name='状态')),
                ('context_summary', models.TextField(blank=True, verbose_name='压缩后的上下文')),
                ('round', models.IntegerField(default=0, verbose_name='当前轮次')),
                ('next_speaker_idx', models.IntegerField(default=0, verbose_name='下一位发言者下标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('participants', models.ManyToManyField(related_name='meetings', to='council.agentprofile', verbose_name='参会 Agent')),
            ],
            options={
                'verbose_name': '会议',
                'verbose_name_plural': '会议',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='方案内容(Markdown)')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='council.meeting')),
            ],
            options={
                'verbose_name': '方案文件',
                'verbose_name_plural': '方案文件',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_type', models.CharField(choices=[('agent', 'Agent'), ('user', '我'), ('system', '系统')], max_length=8, verbose_name='发言方')),
                ('speaker_name', models.CharField(max_length=64, verbose_name='发言者名')),
                ('emoji', models.CharField(default='🙂', max_length=8, verbose_name='头像')),
                ('content', models.TextField(verbose_name='内容')),
                ('round', models.IntegerField(default=0, verbose_name='轮次')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.agentprofile')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='council.meeting')),
            ],
            options={
                'verbose_name': '发言',
                'verbose_name_plural': '发言',
                'ordering': ['id'],
            },
        ),
    ]
