# Generated by Django 5.2.16 on 2026-07-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='group',
            field=models.CharField(blank=True, default='未分类', max_length=64, verbose_name='分类'),
        ),
    ]
