# Generated by Django 5.2.14 on 2026-07-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0003_deliverable_kind_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='content',
            field=models.TextField(verbose_name='内容(文本或 base64)'),
        ),
    ]
