# Generated by Django 5.2.16 on 2026-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0004_alter_deliverable_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='execution_role',
            field=models.CharField(choices=[('operator', '操作员'), ('manager', '主管'), ('director', '总监')], default='operator', max_length=16, verbose_name='执行权限角色'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='可用于任务执行'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='quota_limit',
            field=models.PositiveBigIntegerField(default=10000, verbose_name='任务额度上限'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='quota_used',
            field=models.PositiveBigIntegerField(default=0, verbose_name='已使用额度'),
        ),
    ]
