# Generated by Django 6.0.7 on 2026-07-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0006_seed_execution_agents'),
        ('council', '0007_meetinginvite'),
    ]

    operations = [
    ]
