# Generated by Django 5.2.16 on 2026-07-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0008_merge_0006_seed_execution_agents_0007_meetinginvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meetinginvite',
            new_name='council_mee_user_id_1b3639_idx',
            old_name='council_mee_user_id_7f9a1c_idx',
        ),
    ]
