# Generated by Django 5.2.16 on 2026-07-23 01:28
# Keep only the MeetingInvite index rename. AgentProfile fields belong to
# 0009_agentprofile_enterprise_capabilities (parallel merge branch).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("council", "0009_rename_council_mee_user_id_7f9a1c_idx_council_mee_user_id_1b3639_idx"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="meetinginvite",
            new_name="council_mee_user_id_7f9a1c_idx",
            old_name="council_mee_user_id_1b3639_idx",
        ),
    ]
