# Generated by Django 5.2.16 on 2026-07-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0010_agentprofile_sop_keys'),
        ('council', '0010_rename_council_mee_user_id_1b3639_idx_council_mee_user_id_7f9a1c_idx_and_more'),
    ]

    operations = [
    ]
