# Generated by Django 5.2.16 on 2026-07-17 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_sheets', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '智能表格',
                'verbose_name_plural': '智能表格',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SmartRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=dict, verbose_name='单元格')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='smarttable.smartsheet', verbose_name='所属表格')),
            ],
            options={
                'verbose_name': '表格行',
                'verbose_name_plural': '表格行',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SmartColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='字段键')),
                ('title', models.CharField(max_length=120, verbose_name='列名')),
                ('field_type', models.CharField(choices=[('text', '文本'), ('number', '数字'), ('select', '单选'), ('checkbox', '勾选'), ('date', '日期')], default='text', max_length=16, verbose_name='类型')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='选项')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='smarttable.smartsheet', verbose_name='所属表格')),
            ],
            options={
                'verbose_name': '表格列',
                'verbose_name_plural': '表格列',
                'ordering': ['position', 'id'],
                'unique_together': {('sheet', 'key')},
            },
        ),
    ]
