# Generated by Django 5.2.16 on 2026-07-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcolumn',
            name='field_type',
            field=models.CharField(choices=[('text', '文本'), ('number', '数字'), ('select', '单选'), ('multi_select', '多选'), ('checkbox', '勾选'), ('date', '日期'), ('person', '人员')], default='text', max_length=16, verbose_name='类型'),
        ),
    ]
