# Generated by Django 5.2.16 on 2026-07-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttable', '0003_baserow_sso_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('trigger', models.CharField(choices=[('row_created', '新增记录时'), ('row_updated', '更新记录时')], max_length=32)),
                ('action', models.CharField(choices=[('set_field', '设置字段值')], max_length=32)),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='smarttable.smartsheet', verbose_name='所属表格')),
            ],
            options={
                'verbose_name': '自动化',
                'verbose_name_plural': '自动化',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SmartView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='视图名')),
                ('view_type', models.CharField(choices=[('grid', '表格'), ('kanban', '看板'), ('form', '表单')], default='grid', max_length=16, verbose_name='类型')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='smarttable.smartsheet', verbose_name='所属表格')),
            ],
            options={
                'verbose_name': '视图',
                'verbose_name_plural': '视图',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='BaserowSsoTicket',
        ),
    ]
