# Generated by Django 5.2.16 on 2026-07-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64, verbose_name='链路ID')),
                ('actor', models.CharField(default='agent', max_length=128, verbose_name='发起人')),
                ('intent', models.CharField(blank=True, max_length=128, verbose_name='意图')),
                ('action', models.CharField(blank=True, max_length=128, verbose_name='动作')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='动作参数')),
                ('decision', models.CharField(choices=[('allow', '放行'), ('block', '拦截'), ('need_approval', '待人工审批'), ('dry_run', '预执行')], default='dry_run', max_length=20, verbose_name='闸机结论')),
                ('checks', models.JSONField(blank=True, default=list, verbose_name='校验明细')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
