# Generated by Django 5.2.16 on 2026-07-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='标准化手机号哈希'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='phone_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='手机号更新时间'),
        ),
    ]
