# Generated by Django 5.2.16 on 2026-07-16 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_taskresultrecord_taskfollowup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('sop_id', models.CharField(blank=True, default='', max_length=128)),
                ('agent_name', models.CharField(blank=True, default='', max_length=128)),
                ('priority', models.CharField(choices=[('normal', '普通'), ('high', '高'), ('urgent', '紧急')], db_index=True, default='normal', max_length=16)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '执行中'), ('completed', '已完成'), ('partial', '部分完成'), ('failed', '执行失败')], db_index=True, default='running', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('assignee_wecom_userids', models.JSONField(blank=True, default=list)),
                ('assignee_names', models.JSONField(blank=True, default=list)),
                ('notification_mode', models.CharField(blank=True, default='', max_length=16)),
                ('notification_target', models.CharField(blank=True, default='', max_length=500)),
                ('notification_status', models.CharField(blank=True, default='pending', max_length=32)),
                ('notification_record_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='received_work_tasks', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_work_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['sender', 'status'], name='work_task_sender_status'), models.Index(fields=['priority', 'deadline'], name='work_task_priority_deadline')],
                'constraints': [models.UniqueConstraint(fields=('sender', 'trace_id'), name='uniq_work_task_sender_trace')],
            },
        ),
    ]
