# Generated by Django 5.2.16 on 2026-07-16 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_worktask'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTaskArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('md', 'Markdown 文档'), ('json', 'JSON 数据'), ('xlsx', 'Excel 工作簿')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('content', models.BinaryField()),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.worktask')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('task', 'kind'), name='uniq_work_task_artifact_kind')],
            },
        ),
    ]
