# Generated by Django 5.2.16 on 2026-07-16 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organization_organizationmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'owner')), fields=('organization',), name='uniq_active_owner_per_organization'),
        ),
    ]
