# Generated by Django 5.2.16 on 2026-07-17 01:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_organizationmembership_uniq_active_owner_per_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('normal', '普通'), ('high', '高'), ('urgent', '紧急')], db_index=True, default='normal', max_length=16)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('remind_types', models.JSONField(blank=True, default=list)),
                ('wecom_todo_id_encrypted', models.TextField(blank=True, default='')),
                ('sync_status', models.CharField(choices=[('pending', '待同步'), ('synced', '已同步'), ('failed', '同步失败')], db_index=True, default='pending', max_length=16)),
                ('sync_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('sync_error_reason', models.CharField(blank=True, default='', max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_work_todos', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_work_todos', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_todos', to='core.organization')),
            ],
            options={
                'ordering': ['status', 'due_at', '-created_at', 'id'],
                'indexes': [models.Index(fields=['organization', 'assignee', 'status'], name='todo_org_assignee_status'), models.Index(fields=['organization', 'creator', 'status'], name='todo_org_creator_status')],
            },
        ),
    ]
