# Generated by Django 5.2.16 on 2026-07-20 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_usersettings_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='团队名称')),
                ('kind', models.CharField(choices=[('platform', '平台团队'), ('enterprise', '企业团队')], db_index=True, default='enterprise', max_length=16, verbose_name='团队类型')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='团队说明')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('organization', models.ForeignKey(blank=True, help_text='企业团队归属的企业；平台团队为空。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.organization', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队',
                'ordering': ['kind', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', '团队负责人'), ('member', '团队成员')], db_index=True, default='member', max_length=16, verbose_name='团队角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.team', verbose_name='团队')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['team_id', 'role', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='uniq_team_user')],
            },
        ),
    ]
