# Generated by Django 5.2.16 on 2026-07-20 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_workautomation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_source', models.CharField(max_length=24)),
                ('trace_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('blocked', '规则阻止'), ('need_input', '需要补充信息'), ('need_approval', '等待审批')], db_index=True, default='running', max_length=24)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, default='', max_length=32)),
                ('action_name', models.CharField(blank=True, default='', max_length=128)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('error', models.CharField(blank=True, default='', max_length=1000)),
                ('notification_status', models.CharField(blank=True, default='', max_length=32)),
                ('notification_record_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='workautomation',
            name='claim_token',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workautomation',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workautomation',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='workautomation',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workautomation',
            name='last_run_status',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='workautomation',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workautomation',
            name='run_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workautomation',
            name='trigger_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='workautomation',
            index=models.Index(fields=['enabled', 'trigger_type', 'next_run_at'], name='automation_due_idx'),
        ),
        migrations.AddField(
            model_name='workautomationrun',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.workautomation'),
        ),
        migrations.AddField(
            model_name='workautomationrun',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_automation_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workautomationrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_automation_runs', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='workautomationrun',
            index=models.Index(fields=['organization', 'creator', 'started_at'], name='automation_run_user_idx'),
        ),
        migrations.AddIndex(
            model_name='workautomationrun',
            index=models.Index(fields=['automation', 'status'], name='automation_run_status_idx'),
        ),
    ]
