# Generated by Django 5.2.16 on 2026-07-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_tasktemplate_builtin_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktaskartifact',
            name='kind',
            field=models.CharField(choices=[('md', 'Markdown 文档'), ('html', 'HTML 报告'), ('json', 'JSON 数据'), ('xlsx', 'Excel 工作簿')], max_length=16),
        ),
    ]
