# Generated by Django 5.2.16 on 2026-07-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sop_evolution_observability'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sop_evolution_enabled',
            field=models.BooleanField(default=True, verbose_name='启用 SOP 自我进化'),
        ),
    ]
