"""Protocol and local materialization for files generated by the chat agent."""
from __future__ import annotations

import csv
import html
import io
import json
import mimetypes
import re
from dataclasses import dataclass
from pathlib import Path

from .attachments import store_generated_attachment


SUPPORTED_EXTENSIONS = {".html", ".htm", ".md", ".markdown", ".txt", ".json", ".csv"}
_ARTIFACT_MARKER_RE = re.compile(
    r'<<<LIANGCE_ARTIFACT\s+filename="([^"]+)"(?:\s+mime="([^"]+)")?\s*>>>'
    r"\s*(.*?)\s*<<<END_LIANGCE_ARTIFACT>>>",
    re.IGNORECASE | re.DOTALL,
)
_CODE_FENCE_RE = re.compile(r"^```[a-z0-9_-]*\s*\n(.*?)\n```$", re.IGNORECASE | re.DOTALL)
_DANGEROUS_TAG_RE = re.compile(
    r"<\s*(script|iframe|object|embed|form|base|link)\b[^>]*>.*?<\s*/\s*\1\s*>"
    r"|<\s*(script|iframe|object|embed|form|base|link)\b[^>]*/?\s*>",
    re.IGNORECASE | re.DOTALL,
)
_EVENT_HANDLER_RE = re.compile(
    r"\s+on[a-z]+\s*=\s*(?:\"[^\"]*\"|'[^']*'|[^\s>]+)",
    re.IGNORECASE,
)
_EXTERNAL_URL_ATTR_RE = re.compile(
    r"\s+(?:src|href)\s*=\s*([\"'])\s*(?:https?:|//|javascript:)[^\"']*\1",
    re.IGNORECASE,
)
_CSS_EXTERNAL_RE = re.compile(
    r"@import\s+[^;]+;|url\(\s*([\"']?)(?:https?:|//|javascript:).*?\1\s*\)",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class ArtifactRequest:
    extension: str
    fallback_name: str
    mime: str


def _clean_title(message: str) -> str:
    title = re.sub(
        r"(?i)(请|帮我|需要|生成|制作|创建|输出|导出|一个|一份|文件|产物|html|markdown|md|txt|json|csv)",
        " ",
        message,
    )
    title = re.sub(r"[^\w\u4e00-\u9fff-]+", "-", title).strip("-_ ")
    return (title[:28] or "AI分析报告").rstrip("-_ ")


def detect_artifact_request(message: str) -> ArtifactRequest | None:
    text = (message or "").strip()
    lower = text.lower()
    if not text:
        return None

    extension = ""
    explicit = re.search(r"\.(html?|md|markdown|txt|json|csv)\b", lower)
    if explicit:
        extension = f".{explicit.group(1)}"
    elif (
        ("html" in lower and any(term in text for term in ("文件", "报告", "产物", "网页")))
        or any(term in text for term in ("网页报告", "图表报告", "可视化报告"))
    ):
        extension = ".html"
    elif re.search(r"\bmarkdown\b|markdown\s*文件", lower):
        extension = ".md"
    elif "json" in lower:
        extension = ".json"
    elif "csv" in lower:
        extension = ".csv"
    elif re.search(r"\btxt\b|文本文件", lower):
        extension = ".txt"
    elif any(term in text for term in ("生成文件", "输出文件", "导出文件", "生成产物", "报告文件")):
        extension = ".html"
    else:
        return None

    extension = ".html" if extension == ".htm" else ".md" if extension == ".markdown" else extension
    mime = mimetypes.guess_type(f"artifact{extension}")[0] or "application/octet-stream"
    return ArtifactRequest(
        extension=extension,
        fallback_name=f"{_clean_title(text)}{extension}",
        mime=mime,
    )


def artifact_system_append(request: ArtifactRequest | None) -> str:
    if request is None:
        return ""
    return f"""

The user explicitly asked for a real downloadable file artifact.
Create the requested {request.extension} file, not merely a prose description.
After a short user-facing confirmation, include exactly one complete file payload with these markers:
<<<LIANGCE_ARTIFACT filename="{request.fallback_name}" mime="{request.mime}">>>
...complete file contents...
<<<END_LIANGCE_ARTIFACT>>>
Do not wrap the markers in a Markdown code fence. For HTML, produce a self-contained static report
using only HTML/CSS/inline SVG: no scripts, remote resources, forms, iframes, or external URLs.
"""


def _safe_filename(filename: str, request: ArtifactRequest) -> str:
    name = Path((filename or "").replace("\\", "/")).name
    name = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "-", name).strip(" .")
    ext = Path(name.lower()).suffix
    if ext not in SUPPORTED_EXTENSIONS:
        name = f"{Path(name).stem or Path(request.fallback_name).stem}{request.extension}"
    return name[:120] or request.fallback_name


def _strip_code_fence(content: str) -> str:
    match = _CODE_FENCE_RE.match(content.strip())
    return match.group(1).strip() if match else content.strip()


def sanitize_static_html(content: str) -> str:
    safe = _DANGEROUS_TAG_RE.sub("", content)
    safe = _EVENT_HANDLER_RE.sub("", safe)
    safe = _EXTERNAL_URL_ATTR_RE.sub("", safe)
    safe = _CSS_EXTERNAL_RE.sub("", safe)
    safe = re.sub(r"<meta\b[^>]*http-equiv[^>]*>", "", safe, flags=re.IGNORECASE)
    if not re.search(r"<html\b", safe, re.IGNORECASE):
        safe = (
            "<!doctype html><html lang=\"zh-CN\"><head><meta charset=\"utf-8\">"
            "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
            "</head><body>"
            f"{safe}</body></html>"
        )
    return safe


def _metric_rows(reply: str) -> list[tuple[str, float, str]]:
    matches = re.findall(
        r"([\w\u4e00-\u9fff· /-]{2,24})[：:\s]+(-?\d+(?:\.\d+)?)\s*(%|万|亿|元|件|个|次)?",
        reply,
    )
    rows: list[tuple[str, float, str]] = []
    for label, raw_value, unit in matches:
        clean_label = re.sub(r"\s+", " ", label).strip(" -*#")
        try:
            value = float(raw_value)
        except ValueError:
            continue
        if clean_label and all(clean_label != existing[0] for existing in rows):
            rows.append((clean_label[-18:], value, unit or ""))
        if len(rows) >= 6:
            break
    return rows


def _fallback_html(request: ArtifactRequest, reply: str) -> str:
    title = html.escape(Path(request.fallback_name).stem)
    paragraphs = [
        f"<p>{html.escape(part.strip()).replace(chr(10), '<br>')}</p>"
        for part in re.split(r"\n\s*\n", reply)
        if part.strip()
    ]
    metrics = _metric_rows(reply)
    chart = ""
    if metrics:
        maximum = max(abs(value) for _, value, _ in metrics) or 1
        bars = "".join(
            (
                "<div class=\"metric-row\">"
                f"<span>{html.escape(label)}</span>"
                f"<i><b style=\"width:{max(4, min(100, abs(value) / maximum * 100)):.1f}%\"></b></i>"
                f"<strong>{value:g}{html.escape(unit)}</strong>"
                "</div>"
            )
            for label, value, unit in metrics
        )
        chart = f"<section><h2>关键指标</h2><div class=\"chart\">{bars}</div></section>"
    return sanitize_static_html(f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>
    :root {{ color-scheme: light; --ink:#172033; --muted:#69758a; --accent:#315efb; --gold:#c58b35; }}
    * {{ box-sizing:border-box; }}
    body {{ margin:0; padding:38px; color:var(--ink); background:#f4f7fb;
      font:15px/1.75 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif; }}
    main {{ max-width:980px; margin:auto; overflow:hidden; border:1px solid #e4eaf3; border-radius:24px;
      background:#fff; box-shadow:0 24px 70px rgba(29,45,75,.11); }}
    header {{ padding:38px 42px; color:#fff; background:linear-gradient(135deg,#0c2c54,#315efb 72%,#6f55e8); }}
    header small {{ opacity:.76; letter-spacing:.18em; text-transform:uppercase; }}
    h1 {{ margin:8px 0 4px; font-size:32px; line-height:1.25; }}
    .content {{ padding:34px 42px 42px; }}
    section {{ margin:0 0 28px; }}
    h2 {{ margin:0 0 14px; font-size:18px; }}
    p {{ margin:0 0 14px; color:#3b465a; }}
    .chart {{ display:grid; gap:13px; padding:22px; border:1px solid #e8edf5; border-radius:18px; background:#f8faff; }}
    .metric-row {{ display:grid; grid-template-columns:minmax(90px,180px) 1fr 90px; align-items:center; gap:14px; }}
    .metric-row span {{ overflow:hidden; color:var(--muted); text-overflow:ellipsis; white-space:nowrap; }}
    .metric-row i {{ height:10px; overflow:hidden; border-radius:999px; background:#e6ecf7; }}
    .metric-row b {{ display:block; height:100%; border-radius:inherit; background:linear-gradient(90deg,var(--accent),#8a6df0); }}
    .metric-row strong {{ text-align:right; }}
    footer {{ padding-top:22px; border-top:1px solid #edf0f5; color:var(--muted); font-size:12px; }}
    @media (max-width:640px) {{ body{{padding:12px}} header,.content{{padding:24px}} .metric-row{{grid-template-columns:80px 1fr 58px}} }}
  </style>
</head>
<body>
  <main>
    <header><small>Liangce AI Artifact</small><h1>{title}</h1><div>由小策bot生成的静态可预览报告</div></header>
    <div class="content">
      {chart}
      <section><h2>分析内容</h2>{''.join(paragraphs) or '<p>暂无正文。</p>'}</section>
      <footer>该文件是本次对话的真实产物，可下载、预览并在后续对话中继续引用。</footer>
    </div>
  </main>
</body>
</html>""")


def _fallback_payload(request: ArtifactRequest, reply: str) -> str:
    if request.extension == ".html":
        return _fallback_html(request, reply)
    if request.extension == ".json":
        return json.dumps(
            {"title": Path(request.fallback_name).stem, "content": reply},
            ensure_ascii=False,
            indent=2,
        )
    if request.extension == ".csv":
        stream = io.StringIO()
        writer = csv.writer(stream)
        writer.writerow(["section", "content"])
        for index, paragraph in enumerate(re.split(r"\n\s*\n", reply), 1):
            if paragraph.strip():
                writer.writerow([index, paragraph.strip()])
        return stream.getvalue()
    if request.extension == ".md":
        return f"# {Path(request.fallback_name).stem}\n\n{reply.strip()}\n"
    return reply.strip() + "\n"


def materialize_generated_artifacts(
    *,
    message: str,
    reply: str,
    user_id: int,
) -> tuple[str, list[dict]]:
    request = detect_artifact_request(message)
    if request is None:
        return reply, []

    marker_matches = list(_ARTIFACT_MARKER_RE.finditer(reply))
    artifacts: list[dict] = []
    for match in marker_matches[:3]:
        filename = _safe_filename(match.group(1), request)
        content = _strip_code_fence(match.group(3))
        extension = Path(filename.lower()).suffix
        if extension in {".html", ".htm"}:
            content = sanitize_static_html(content)
        mime = match.group(2) or mimetypes.guess_type(filename)[0] or request.mime
        artifacts.append(
            store_generated_attachment(
                payload=content.encode("utf-8"),
                filename=filename,
                user_id=user_id,
                mime=mime,
            )
        )

    visible_reply = _ARTIFACT_MARKER_RE.sub("", reply).strip()
    if not artifacts:
        fallback = _fallback_payload(request, reply)
        artifacts.append(
            store_generated_attachment(
                payload=fallback.encode("utf-8"),
                filename=request.fallback_name,
                user_id=user_id,
                mime=request.mime,
            )
        )
    if not visible_reply:
        visible_reply = f"已生成可预览、可下载的文件：{artifacts[0]['name']}"
    elif artifacts and artifacts[0]["name"] not in visible_reply:
        visible_reply = f"{visible_reply.rstrip()}\n\n已生成文件：`{artifacts[0]['name']}`"
    return visible_reply, artifacts
