# Generated by Django 5.2.16 on 2026-07-22 03:21

import apps.datalake.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_platform_team_creator_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_id', models.CharField(max_length=64)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('formula', models.TextField()),
                ('unit', models.CharField(max_length=32)),
                ('dimensions', models.JSONField(default=list)),
                ('time_window', models.JSONField(default=dict)),
                ('missing_policy', models.CharField(default='block', max_length=32)),
                ('contract_hash', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='为空表示平台内置契约。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_contracts', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_key', models.CharField(default=apps.datalake.models.new_snapshot_key, max_length=96)),
                ('source_system', models.CharField(max_length=64)),
                ('source_mode', models.CharField(choices=[('live', '真实来源'), ('fixture', '样例'), ('mock', '模拟')], default='live', max_length=16)),
                ('scope', models.JSONField(default=dict)),
                ('as_of', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('completeness', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.CharField(max_length=32)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_snapshots', to='core.organization')),
            ],
            options={
                'ordering': ['-as_of', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MetricResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=32)),
                ('dimensions', models.JSONField(default=dict)),
                ('as_of', models.DateTimeField()),
                ('query_fingerprint', models.CharField(max_length=80)),
                ('result_fingerprint', models.CharField(max_length=80)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='datalake.metriccontract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_results', to='core.organization')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metric_results', to='datalake.sourcesnapshot')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='metriccontract',
            constraint=models.UniqueConstraint(fields=('organization', 'metric_id', 'version'), name='uniq_org_metric_contract'),
        ),
        migrations.AddConstraint(
            model_name='sourcesnapshot',
            constraint=models.UniqueConstraint(fields=('organization', 'snapshot_key'), name='uniq_org_snapshot_key'),
        ),
        migrations.AddConstraint(
            model_name='metricresult',
            constraint=models.UniqueConstraint(fields=('organization', 'contract', 'snapshot', 'query_fingerprint'), name='uniq_metric_result_fingerprint'),
        ),
    ]
