# Generated by Django 5.2.16 on 2026-07-22 03:56

import apps.datalake.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_platform_team_creator_membership'),
        ('datalake', '0002_seed_metric_contracts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesnapshot',
            name='boundary_covered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sourcesnapshot',
            name='governance_status',
            field=models.CharField(default='legacy_accepted', max_length=24),
        ),
        migrations.AddField(
            model_name='sourcesnapshot',
            name='manifest_hash',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='sourcesnapshot',
            name='reconciliation_status',
            field=models.CharField(default='not_required', max_length=24),
        ),
        migrations.AddField(
            model_name='sourcesnapshot',
            name='source_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='metricresult',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.CreateModel(
            name='ImportContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_key', models.CharField(max_length=96)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('dataset_type', models.CharField(default='sales_ledger', max_length=64)),
                ('schema', models.JSONField(default=dict)),
                ('contract_hash', models.CharField(max_length=80)),
                ('signoff_status', models.CharField(choices=[('candidate', '候选'), ('confirmed', '已确认'), ('archived', '已归档')], default='candidate', max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_import_contracts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datalake_import_contracts', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceMappingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_key', models.CharField(max_length=96)),
                ('kind', models.CharField(choices=[('channel', '渠道'), ('product', '商品'), ('warehouse', '仓库')], max_length=16)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('mappings', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('candidate', '候选'), ('confirmed', '已确认'), ('archived', '已归档')], default='candidate', max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_mapping_sets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_mapping_sets', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RawImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_key', models.CharField(default=apps.datalake.models.new_raw_import_key, max_length=96)),
                ('dataset_type', models.CharField(default='sales_ledger', max_length=64)),
                ('source_system', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', '处理中'), ('quarantined', '待对账'), ('ready', '可生成快照'), ('rejected', '已拒绝')], default='processing', max_length=16)),
                ('reconciliation_status', models.CharField(choices=[('pending', '待对账'), ('passed', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=16)),
                ('manifest_hash', models.CharField(max_length=80)),
                ('content_hash', models.CharField(max_length=80)),
                ('schema_version', models.CharField(max_length=32)),
                ('window_start', models.DateField(blank=True, null=True)),
                ('window_end', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('boundary_covered', models.BooleanField(default=False)),
                ('source_complete', models.BooleanField(default=False)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('accepted_row_count', models.PositiveIntegerField(default=0)),
                ('quarantine_summary', models.JSONField(blank=True, default=dict)),
                ('quality_signals', models.JSONField(blank=True, default=dict)),
                ('aggregate_receipt', models.JSONField(blank=True, default=dict)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='datalake.importcontract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_import_batches', to='core.organization')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_raw_imports', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_import_batch', to='datalake.sourcesnapshot')),
                ('channel_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_import_batches', to='datalake.referencemappingset')),
                ('product_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_import_batches', to='datalake.referencemappingset')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='importcontract',
            constraint=models.UniqueConstraint(fields=('organization', 'contract_key', 'version'), name='uniq_org_import_contract_version'),
        ),
        migrations.AddConstraint(
            model_name='referencemappingset',
            constraint=models.UniqueConstraint(fields=('organization', 'mapping_key', 'version'), name='uniq_org_mapping_version'),
        ),
        migrations.AddConstraint(
            model_name='rawimportbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'import_key'), name='uniq_org_raw_import_key'),
        ),
    ]
