# Generated by Django 5.2.16 on 2026-07-16 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_id",
                    models.CharField(max_length=64, unique=True, verbose_name="模板标识"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="名称")),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="分类"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("compiled", "整编知识"),
                            ("evidence", "证据问答"),
                            ("graph", "关系图谱"),
                            ("hybrid", "混合知识"),
                            ("custom", "自定义"),
                        ],
                        default="hybrid",
                        max_length=16,
                        verbose_name="类型",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("official", "官方"),
                            ("custom", "自定义"),
                            ("experimental", "实验"),
                            ("archived", "归档"),
                        ],
                        default="official",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="一句话说明"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "accepted_file_types",
                    models.JSONField(blank=True, default=list, verbose_name="支持文件类型"),
                ),
                (
                    "default_config",
                    models.JSONField(blank=True, default=dict, verbose_name="默认配置"),
                ),
                (
                    "output_capabilities",
                    models.JSONField(blank=True, default=list, verbose_name="输出能力"),
                ),
                (
                    "limitations",
                    models.JSONField(blank=True, default=list, verbose_name="限制"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "知识库模板",
                "verbose_name_plural": "知识库模板",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="分类"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="database", max_length=64, verbose_name="图标"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "个人"), ("team", "团队"), ("company", "公司")],
                        default="team",
                        max_length=16,
                        verbose_name="可见范围",
                    ),
                ),
                (
                    "retrieval_mode",
                    models.CharField(
                        choices=[
                            ("naive-rag", "证据优先 RAG"),
                            ("graph-rag", "关系图谱 RAG"),
                            ("hybrid-rag", "混合检索"),
                        ],
                        default="hybrid-rag",
                        max_length=24,
                        verbose_name="检索模式",
                    ),
                ),
                (
                    "review_policy",
                    models.CharField(
                        blank=True, default="sample", max_length=24, verbose_name="审核策略"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("processing", "处理中"),
                            ("ready", "可用"),
                            ("review", "待复核"),
                            ("archived", "归档"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="配置"),
                ),
                (
                    "file_count",
                    models.PositiveIntegerField(default=0, verbose_name="文件数"),
                ),
                (
                    "app_count",
                    models.PositiveIntegerField(default=0, verbose_name="关联应用数"),
                ),
                (
                    "recall_count",
                    models.PositiveIntegerField(default=0, verbose_name="召回次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="归档时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_bases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_bases",
                        to="knowledge.knowledgetemplate",
                        verbose_name="模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库",
                "verbose_name_plural": "知识库",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="文件类型"
                    ),
                ),
                (
                    "segment_mode",
                    models.CharField(
                        blank=True,
                        default="general",
                        max_length=32,
                        verbose_name="分段模式",
                    ),
                ),
                (
                    "char_count",
                    models.PositiveIntegerField(default=0, verbose_name="字符数"),
                ),
                (
                    "chunk_count",
                    models.PositiveIntegerField(default=0, verbose_name="切片数"),
                ),
                (
                    "recall_count",
                    models.PositiveIntegerField(default=0, verbose_name="召回次数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "已上传"),
                            ("processing", "处理中"),
                            ("ready", "可用"),
                            ("review", "待复核"),
                            ("failed", "失败"),
                            ("archived", "归档"),
                        ],
                        default="uploaded",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="存储路径"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=128,
                        verbose_name="内容 Hash",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="归档时间"),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="knowledge.knowledgebase",
                        verbose_name="知识库",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库文件",
                "verbose_name_plural": "知识库文件",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunkRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField(verbose_name="切片序号")),
                (
                    "chunk_ref",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="切片引用"
                    ),
                ),
                (
                    "text_preview",
                    models.TextField(blank=True, default="", verbose_name="文本预览"),
                ),
                (
                    "embedding_ref",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="向量引用"
                    ),
                ),
                (
                    "graph_entity_ref",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="图谱实体引用"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunk_refs",
                        to="knowledge.knowledgefile",
                        verbose_name="文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识切片引用",
                "verbose_name_plural": "知识切片引用",
                "ordering": ["file_id", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeIngestJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待"),
                            ("parsing", "解析中"),
                            ("chunking", "切块中"),
                            ("embedding", "向量化"),
                            ("graphing", "图谱抽取"),
                            ("ready", "完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True, default="pending", max_length=64, verbose_name="阶段"
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(default=0, verbose_name="进度"),
                ),
                ("error", models.JSONField(blank=True, null=True, verbose_name="错误")),
                (
                    "metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="处理指标"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_ingest_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起人",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="knowledge.knowledgefile",
                        verbose_name="文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识入库任务",
                "verbose_name_plural": "知识入库任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("user", "用户"), ("team", "团队"), ("org", "组织")],
                        max_length=16,
                        verbose_name="主体类型",
                    ),
                ),
                ("subject_id", models.CharField(max_length=128, verbose_name="主体 ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "负责人"),
                            ("editor", "编辑者"),
                            ("viewer", "查看者"),
                        ],
                        default="viewer",
                        max_length=16,
                        verbose_name="角色",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="knowledge.knowledgebase",
                        verbose_name="知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库权限",
                "verbose_name_plural": "知识库权限",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeSourceBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("graph", "GraphRAG"),
                            ("wiki", "Wiki"),
                            ("traditional", "Traditional RAG"),
                            ("external", "外部知识库"),
                        ],
                        max_length=24,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="来源 ID"
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="来源名称"
                    ),
                ),
                (
                    "workspace",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="工作空间"
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="绑定配置"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_bindings",
                        to="knowledge.knowledgebase",
                        verbose_name="知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识源绑定",
                "verbose_name_plural": "知识源绑定",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=64, verbose_name="动作")),
                (
                    "target_type",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="目标类型"
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="目标 ID"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="载荷"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="knowledge.knowledgebase",
                        verbose_name="知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库审计",
                "verbose_name_plural": "知识库审计",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["knowledge_base", "created_at"],
                        name="knowledge_k_knowled_0f801f_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="knowledge_k_actor_i_b6347c_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="knowledge_k_action_add9d0_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgefile",
            index=models.Index(
                fields=["knowledge_base", "status", "uploaded_at"],
                name="knowledge_k_knowled_3ddb5c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgefile",
            index=models.Index(
                fields=["knowledge_base", "original_filename"],
                name="knowledge_k_knowled_032dfa_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgechunkref",
            constraint=models.UniqueConstraint(
                fields=("file", "chunk_index"), name="uniq_knowledge_file_chunk_index"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeingestjob",
            index=models.Index(
                fields=["status", "created_at"], name="knowledge_k_status_bcc264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeingestjob",
            index=models.Index(
                fields=["file", "created_at"], name="knowledge_k_file_id_5343c2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgepermission",
            constraint=models.UniqueConstraint(
                fields=("knowledge_base", "subject_type", "subject_id"),
                name="uniq_knowledge_permission_subject",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesourcebinding",
            index=models.Index(
                fields=["knowledge_base", "source_type", "enabled"],
                name="knowledge_k_knowled_d8cec1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesourcebinding",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="knowledge_k_source__b67b00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(
                fields=["status", "updated_at"], name="knowledge_k_status_58e4f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(
                fields=["visibility", "updated_at"],
                name="knowledge_k_visibil_d2e14d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(
                fields=["category", "updated_at"], name="knowledge_k_categor_a10568_idx"
            ),
        ),
    ]
