# Generated by Django 5.2.14 on 2026-07-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64, verbose_name='链路ID')),
                ('action', models.CharField(max_length=128, verbose_name='动作')),
                ('intent', models.CharField(blank=True, max_length=256, verbose_name='意图')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='动作参数')),
                ('role', models.CharField(default='operator', max_length=64, verbose_name='发起角色')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('executed', '已执行')], default='pending', max_length=16, verbose_name='状态')),
                ('checks', models.JSONField(blank=True, default=list, verbose_name='闸机明细')),
                ('dry_run', models.JSONField(blank=True, default=dict, verbose_name='预执行')),
                ('approver', models.CharField(blank=True, default='', max_length=128, verbose_name='审批人')),
                ('comment', models.TextField(blank=True, default='', verbose_name='审批意见')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
            ],
            options={
                'verbose_name': '审批单',
                'verbose_name_plural': '审批单',
                'ordering': ['-created_at'],
            },
        ),
    ]
