# Generated by Django 5.2.16 on 2026-07-08 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OntObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('physical', '物理'), ('virtual', '虚拟')], default='physical', max_length=16, verbose_name='大类')),
                ('otype', models.CharField(default='物体', max_length=32, verbose_name='类型')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='属性')),
                ('x', models.FloatField(default=0, verbose_name='画布 X')),
                ('y', models.FloatField(default=0, verbose_name='画布 Y')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '本体对象',
                'verbose_name_plural': '本体对象',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OntRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='关联', max_length=64, verbose_name='关系')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_relations', to='ontology.ontobject', verbose_name='起点')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_relations', to='ontology.ontobject', verbose_name='终点')),
            ],
            options={
                'verbose_name': '本体关系',
                'verbose_name_plural': '本体关系',
                'ordering': ['id'],
            },
        ),
    ]
