# Generated by Django 5.2.16 on 2026-07-22 03:21

import apps.ontology.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_platform_team_creator_membership'),
        ('ontology', '0002_ontrelation_causal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CausalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.CharField(choices=[('+', '正(+)'), ('-', '负(-)')], max_length=1)),
                ('delay_days', models.FloatField(blank=True, null=True)),
                ('evidence_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('candidate', '候选'), ('confirmed', '已确认'), ('archived', '已归档')], default='candidate', max_length=16)),
                ('maturity', models.CharField(choices=[('hypothesis', '假设'), ('supported', '有证据支持'), ('validated', '已验证')], default='hypothesis', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OntAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=160)),
                ('source_system', models.CharField(default='local', max_length=48)),
                ('status', models.CharField(choices=[('candidate', '候选'), ('confirmed', '已确认'), ('archived', '已归档')], default='candidate', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OntAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(max_length=96)),
                ('value', models.JSONField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('recorded_from', models.DateTimeField(auto_now_add=True)),
                ('recorded_to', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('candidate', '候选'), ('confirmed', '已确认'), ('archived', '已归档')], default='candidate', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='OntEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_key', models.CharField(max_length=96)),
                ('source_type', models.CharField(default='snapshot', max_length=32)),
                ('source_ref', models.CharField(max_length=255)),
                ('content_hash', models.CharField(max_length=80)),
                ('summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OntologyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=80)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ontobject',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ontrelation',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='ontobject',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='ontobject',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_ontology_objects', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='ontobject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ontology_objects', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='ontobject',
            name='object_key',
            field=models.CharField(default=apps.ontology.models.new_object_key, max_length=96, verbose_name='稳定对象标识'),
        ),
        migrations.AddField(
            model_name='ontobject',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ontology_objects', to='core.organization', verbose_name='企业'),
        ),
        migrations.AddField(
            model_name='ontobject',
            name='source_system',
            field=models.CharField(db_index=True, default='local', max_length=48, verbose_name='来源系统'),
        ),
        migrations.AddField(
            model_name='ontobject',
            name='status',
            field=models.CharField(choices=[('candidate', '候选'), ('confirmed', '已确认'), ('archived', '已归档')], db_index=True, default='candidate', max_length=16, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='ontobject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='ontobject',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='ontrelation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ontology_relations', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='ontrelation',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ontology_relations', to='core.organization', verbose_name='企业'),
        ),
        migrations.AddField(
            model_name='ontrelation',
            name='relation_key',
            field=models.CharField(default=apps.ontology.models.new_relation_key, max_length=96, verbose_name='稳定关系标识'),
        ),
        migrations.AddField(
            model_name='ontrelation',
            name='source_system',
            field=models.CharField(db_index=True, default='local', max_length=48, verbose_name='来源系统'),
        ),
        migrations.AddField(
            model_name='ontrelation',
            name='status',
            field=models.CharField(choices=[('candidate', '候选'), ('confirmed', '已确认'), ('archived', '已归档')], db_index=True, default='candidate', max_length=16, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='ontrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='ontrelation',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='ontrelation',
            name='delay_days',
            field=models.FloatField(blank=True, null=True, verbose_name='兼容延迟(天)'),
        ),
        migrations.AlterField(
            model_name='ontrelation',
            name='evidence_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='兼容证据分'),
        ),
        migrations.AlterField(
            model_name='ontrelation',
            name='is_causal_candidate',
            field=models.BooleanField(default=False, verbose_name='兼容因果候选'),
        ),
        migrations.AlterField(
            model_name='ontrelation',
            name='polarity',
            field=models.CharField(blank=True, choices=[('+', '正(+)'), ('-', '负(-)')], default='', max_length=1, verbose_name='兼容因果极性'),
        ),
        migrations.AddConstraint(
            model_name='ontobject',
            constraint=models.UniqueConstraint(fields=('organization', 'object_key'), name='uniq_org_ontology_object_key'),
        ),
        migrations.AddConstraint(
            model_name='ontrelation',
            constraint=models.UniqueConstraint(fields=('organization', 'relation_key'), name='uniq_org_ontology_relation_key'),
        ),
        migrations.AddField(
            model_name='causallink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='causallink',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causal_links', to='core.organization'),
        ),
        migrations.AddField(
            model_name='causallink',
            name='relation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='causal_link', to='ontology.ontrelation'),
        ),
        migrations.AddField(
            model_name='ontalias',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ontology.ontobject'),
        ),
        migrations.AddField(
            model_name='ontalias',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_aliases', to='core.organization'),
        ),
        migrations.AddField(
            model_name='ontassertion',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='ontology.ontobject'),
        ),
        migrations.AddField(
            model_name='ontassertion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_assertions', to='core.organization'),
        ),
        migrations.AddField(
            model_name='ontevidence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ontevidence',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_evidence', to='core.organization'),
        ),
        migrations.AddField(
            model_name='ontassertion',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assertions', to='ontology.ontevidence'),
        ),
        migrations.AddField(
            model_name='causallink',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='causal_links', to='ontology.ontevidence'),
        ),
        migrations.AddField(
            model_name='ontologyversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ontologyversion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_versions', to='core.organization'),
        ),
        migrations.AddConstraint(
            model_name='ontalias',
            constraint=models.UniqueConstraint(fields=('organization', 'alias', 'source_system'), name='uniq_org_alias_source'),
        ),
        migrations.AddConstraint(
            model_name='ontevidence',
            constraint=models.UniqueConstraint(fields=('organization', 'evidence_key'), name='uniq_org_evidence_key'),
        ),
        migrations.AddConstraint(
            model_name='ontologyversion',
            constraint=models.UniqueConstraint(fields=('organization', 'version'), name='uniq_org_ontology_version'),
        ),
    ]
