# Generated by Django 5.2.16 on 2026-07-22 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_tasktemplate_builtin_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SopDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_key', models.CharField(max_length=96)),
                ('name', models.CharField(max_length=128)),
                ('business_domain', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('action_name', models.CharField(blank=True, db_index=True, default='', max_length=96)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=16)),
                ('current_version', models.CharField(blank=True, default='', max_length=32)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sops', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sop_definitions', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_domain', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SopRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trace_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('running', '运行中'), ('need_input', '等待补充'), ('completed', '已完成'), ('failed', '失败'), ('handoff', '转人工')], db_index=True, default='running', max_length=16)),
                ('current_node', models.CharField(blank=True, default='', max_length=96)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_runs', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sop_runs', to=settings.AUTH_USER_MODEL)),
                ('work_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sop_runs', to='core.worktask')),
            ],
        ),
        migrations.CreateModel(
            name='SopNodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('node_key', models.CharField(max_length=96)),
                ('node_type', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '完成'), ('skipped', '跳过'), ('need_input', '等待补充'), ('failed', '失败')], default='running', max_length=16)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='orchestration.soprun')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SopVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('retired', '已停用')], db_index=True, default='draft', max_length=16)),
                ('graph', models.JSONField(default=dict)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('trigger_intents', models.JSONField(blank=True, default=list)),
                ('utterance_examples', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('change_summary', models.CharField(blank=True, default='', max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sop_versions', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orchestration.sopdefinition')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_sop_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='soprun',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='orchestration.sopversion'),
        ),
        migrations.AddConstraint(
            model_name='sopdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'sop_key'), name='orchestration_sop_org_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sopdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('sop_key',), name='orchestration_sop_system_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sopnoderun',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='orchestration_sop_node_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sopversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version'), name='orchestration_sop_version_uniq'),
        ),
    ]
