# Generated by Django 5.2.16 on 2026-07-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0003_relax_system_report_inputs'),
        ('orchestration', '0004_sopversion_editor_chat'),
    ]

    operations = [
    ]
