# Generated by Django 5.2.16 on 2026-07-23 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sop_evolution_observability'),
        ('orchestration', '0005_merge_20260723_1456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SopEvolutionSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(blank=True, db_index=True, default='', max_length=96)),
                ('signal_type', models.CharField(choices=[('need_input_loop', '反复等待输入'), ('checkpoint_reject', '确认驳回'), ('action_fail', '动作失败'), ('handoff', '转人工'), ('slow_node', '节点耗时过长'), ('unused_branch', '分支很少走到'), ('missing_field_repeat', '字段反复缺失')], db_index=True, max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('sample_run_ids', models.JSONField(blank=True, default=list)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_seen_at', '-count'],
            },
        ),
        migrations.AlterModelOptions(
            name='soprun',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='sopdefinition',
            name='trial_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soprun',
            name='is_trial',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='soprun',
            name='outcome_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='soprun',
            name='source',
            field=models.CharField(choices=[('live', '正式'), ('trial', '试跑'), ('resume', '续跑')], db_index=True, default='live', max_length=16),
        ),
        migrations.AddIndex(
            model_name='soprun',
            index=models.Index(fields=['organization', '-started_at'], name='orch_soprun_org_started_idx'),
        ),
        migrations.AddField(
            model_name='sopevolutionsignal',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_signals', to='orchestration.sopdefinition'),
        ),
        migrations.AddField(
            model_name='sopevolutionsignal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sop_evolution_signals', to='core.organization'),
        ),
        migrations.AddField(
            model_name='sopevolutionsignal',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_signals', to='orchestration.sopversion'),
        ),
        migrations.AddConstraint(
            model_name='sopevolutionsignal',
            constraint=models.UniqueConstraint(fields=('definition', 'node_key', 'signal_type'), name='orchestration_sop_evolution_signal_uniq'),
        ),
    ]
