# Generated by Django 5.2.16 on 2026-07-23 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sop_evolution_observability'),
        ('orchestration', '0007_backfill_soprun_trial_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SopEvolutionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', '已提出'), ('validated', '已校验'), ('trial_passed', '试跑通过'), ('trial_failed', '试跑失败'), ('drafted', '已生成草稿'), ('accepted', '已采纳'), ('rejected', '已拒绝'), ('expired', '已过期')], db_index=True, default='proposed', max_length=16)),
                ('category', models.CharField(choices=[('graph', '流程'), ('skill', '技能'), ('policy', '策略')], db_index=True, default='graph', max_length=16)),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], db_index=True, default='low', max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('rationale', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('patch', models.JSONField(blank=True, default=dict)),
                ('proposed_graph', models.JSONField(blank=True, default=dict)),
                ('trial_result', models.JSONField(blank=True, default=dict)),
                ('created_by_system', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_proposals_base', to='orchestration.sopversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sop_evolution_proposals', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_proposals', to='orchestration.sopdefinition')),
                ('draft_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_proposals_draft', to='orchestration.sopversion')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sop_evolution_proposals', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sop_evolution_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
