# Generated by Django 5.2.16 on 2026-07-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0005_merge_20260723_1130'),
        ('orchestration', '0008_sop_evolution_proposals'),
    ]

    operations = [
    ]
