# Generated by Django 5.2.16 on 2026-07-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0009_merge_20260723_1625'),
        ('orchestration', '0009_merge_20260723_1635'),
    ]

    operations = [
    ]
