# Generated by Django 5.2.16 on 2026-07-20 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_asset_owners(apps, schema_editor):
    SkillAsset = apps.get_model('skills', 'SkillAsset')
    for asset in SkillAsset.objects.filter(owner__isnull=True).iterator():
        asset.owner_id = asset.uploader_id
        asset.save(update_fields=['owner'])


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skillasset_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skillasset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_skill_assets', to=settings.AUTH_USER_MODEL, verbose_name='责任人'),
        ),
        migrations.RunPython(assign_existing_asset_owners, migrations.RunPython.noop),
        migrations.CreateModel(
            name='SkillUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(db_index=True, max_length=64, verbose_name='Skill ID')),
                ('skill_name', models.CharField(blank=True, default='', max_length=128, verbose_name='技能名称')),
                ('source', models.CharField(choices=[('agent', 'Agent 对话'), ('collab', '协作会话'), ('direct', '直接调用')], default='agent', max_length=16, verbose_name='调用方式')),
                ('used_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='调用时间')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='skills.skillasset', verbose_name='来源技能')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_usage_events', to=settings.AUTH_USER_MODEL, verbose_name='调用人')),
            ],
            options={
                'verbose_name': 'Skill 使用事件',
                'verbose_name_plural': 'Skill 使用事件',
                'ordering': ['-used_at', '-id'],
                'indexes': [models.Index(fields=['skill_id', 'used_at'], name='skill_usage_skill_time'), models.Index(fields=['user', 'used_at'], name='skill_usage_user_time')],
            },
        ),
    ]
