# Generated by Django 5.2.14 on 2026-07-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McpServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='服务 ID')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='MCP URL')),
                ('command', models.CharField(blank=True, default='', max_length=255, verbose_name='stdio command')),
                ('args', models.JSONField(blank=True, default=list, verbose_name='stdio args')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'MCP 服务配置',
                'verbose_name_plural': 'MCP 服务配置',
            },
        ),
    ]
