# Generated by Django 5.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0001_mcp_server_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserverconfig",
            name="env",
            field=models.JSONField(blank=True, default=dict, verbose_name="环境变量"),
        ),
    ]
