# Generated by Django 5.2.16 on 2026-07-20 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('user', '用户级'), ('session', '会话级')], db_index=True, default='user', max_length=16, verbose_name='范围')),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='会话 UUID')),
                ('kind', models.CharField(choices=[('fact', '事实'), ('preference', '偏好'), ('summary', '摘要')], db_index=True, default='fact', max_length=16, verbose_name='类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('source', models.CharField(blank=True, default='', max_length=64, verbose_name='来源')),
                ('importance', models.PositiveSmallIntegerField(default=5, verbose_name='重要度')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memory_items', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Agent 记忆',
                'verbose_name_plural': 'Agent 记忆',
                'ordering': ['-importance', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'scope'], name='agentctx_mem_user_scope'), models.Index(fields=['user', 'kind'], name='agentctx_mem_user_kind')],
            },
        ),
        migrations.CreateModel(
            name='AgentSessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=128, verbose_name='会话键')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('message_count', models.PositiveIntegerField(default=0, verbose_name='消息计数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_session_summaries', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会话摘要',
                'verbose_name_plural': '会话摘要',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'session_key'], name='agentctx_sum_user_sess')],
                'constraints': [models.UniqueConstraint(fields=('user', 'session_key'), name='agentctx_summary_user_session_uniq')],
            },
        ),
    ]
