import type { LevelModel, LoopLevel } from "./types";

const c = {
  navy: "#0B2144",
  blue: "#1677ff",
  teal: "#0f766e",
  green: "#15803d",
  orange: "#ea580c",
  purple: "#6d28d9",
  rose: "#be123c",
  gold: "#B8863B",
  slate: "#475569",
};

/** 公司层：对齐 8 Stock 简图 A–E */
const company: LevelModel = {
  level: "company",
  title: "公司层 · 品牌代理 8 Stock",
  subtitle: "全公司多品牌聚合。S4/S8 由下层销售额与运营资源上卷。",
  viewW: 980,
  viewH: 520,
  rollupHint: "本层为最粗粒度；点 Stock 可下钻到品牌实例。",
  drillHint: "点击 S1/S4/S8 等节点 → 进入品牌层样例。",
  stocks: [
    { id: "s1", code: "S1", label: "代理品牌数", sub: "签约规模", x: 48, y: 188, w: 132, h: 72, color: c.blue, soft: "#dbe7ff", drillLevel: "brand" },
    { id: "s2", code: "S2", label: "渠道覆盖密度", sub: "铺货渗透", x: 260, y: 56, w: 140, h: 72, color: "#0369a1", soft: "#d7eef8", drillLevel: "brand" },
    { id: "s3", code: "S3", label: "市场认知", sub: "品牌可见度", x: 500, y: 56, w: 132, h: 72, color: c.teal, soft: "#d5efeb", drillLevel: "brand" },
    { id: "s4", code: "S4", label: "终端销售额", sub: "出货结果", x: 740, y: 188, w: 132, h: 72, color: c.green, soft: "#d9f0e2", drillLevel: "brand" },
    { id: "s5", code: "S5", label: "品牌方满意度", sub: "信任 / 续约", x: 420, y: 400, w: 148, h: 72, color: c.gold, soft: "#f6e6d0", drillLevel: "brand" },
    { id: "s6", code: "S6", label: "团队服务产能", sub: "人才密度", x: 48, y: 380, w: 140, h: 72, color: c.purple, soft: "#ebe4ff" },
    { id: "s7", code: "S7", label: "代理运营能力", sub: "服务质量", x: 280, y: 256, w: 140, h: 72, color: "#4338ca", soft: "#e0e3ff" },
    { id: "s8", code: "S8", label: "运营资源健康", sub: "库存/物流/现金", x: 600, y: 360, w: 148, h: 72, color: c.rose, soft: "#f8dce3", drillLevel: "brand" },
  ],
  flows: [
    { id: "e1", from: "s1", to: "s2", polarity: "+", chains: ["A"], label: "扩渠", bend: -0.12 },
    { id: "e2", from: "s2", to: "s3", polarity: "+", chains: ["A"], label: "可见", bend: 0 },
    { id: "e3", from: "s3", to: "s4", polarity: "+", chains: ["A"], label: "转化", bend: 0.12 },
    { id: "e4", from: "s4", to: "s5", polarity: "+", chains: ["A", "C"], label: "业绩", bend: 0.2 },
    { id: "e5", from: "s5", to: "s1", polarity: "+", chains: ["A", "B", "D"], label: "续约/拓品", bend: 0.28 },
    { id: "e6", from: "s1", to: "s6", polarity: "-", chains: ["B"], label: "稀释产能", bend: 0.15 },
    { id: "e7", from: "s6", to: "s7", polarity: "+", chains: ["B", "D"], label: "交付", bend: -0.08 },
    { id: "e8", from: "s7", to: "s5", polarity: "+", chains: ["B", "C", "D"], label: "体验", bend: 0.1 },
    { id: "e9", from: "s7", to: "s4", polarity: "+", chains: ["C", "E"], label: "运营拉动", bend: -0.18 },
    { id: "e10", from: "s8", to: "s7", polarity: "+", chains: ["C", "E"], label: "资源支撑", bend: -0.12 },
    { id: "e11", from: "s4", to: "s8", polarity: "-", delay: true, chains: ["E"], label: "消耗资源", bend: 0.22 },
  ],
  chains: [
    { id: "all", name: "全貌", color: "#64748b", desc: "8 Stock 因果骨架" },
    { id: "A", name: "A 增长链", color: "#ea580c", desc: "S1→S2→S3→S4→S5→S1 品牌代理飞轮" },
    { id: "B", name: "B 约束链", color: "#2563eb", desc: "S1⊖S6→S7→S5→S1 管理带宽约束" },
    { id: "C", name: "C 资源链", color: "#7c3aed", desc: "S8→S7→S4→S5 运营资源支撑" },
    { id: "D", name: "D 人才链", color: "#0f766e", desc: "S6→S7→S5→S1 人才能力飞轮" },
    { id: "E", name: "E 销资反馈", color: "#be123c", desc: "S4⊖//S8→S7→S4 销售耗资源" },
  ],
  loops: [
    { code: "R1", kind: "R", name: "品牌代理飞轮", path: "S1→S2→S3→S4→S5→S1", chains: ["A"], edgeIds: ["e1", "e2", "e3", "e4", "e5"] },
    { code: "B1", kind: "B", name: "管理带宽约束", path: "S1⊖S6→S7→S5→S1", chains: ["B"], edgeIds: ["e6", "e7", "e8", "e5"] },
    { code: "C1", kind: "C", name: "资源支撑链", path: "S8→S7→S4→S5", chains: ["C"], edgeIds: ["e10", "e9", "e4"] },
    { code: "B3", kind: "B", name: "销资挤兑", path: "S4⊖//S8→S7→S4", chains: ["E"], edgeIds: ["e11", "e10", "e9"] },
  ],
};

const brand: LevelModel = {
  level: "brand",
  title: "品牌层 · 多平台利润池",
  subtitle: "单品牌跨平台汇总。销售额与资源健康继续下钻到平台。",
  viewW: 960,
  viewH: 500,
  rollupHint: "上卷至公司：影响 S1 品牌规模、S4 销售、S5 满意度。",
  drillHint: "点击销售额 / 流量 / 资源节点 → 平台层。",
  stocks: [
    { id: "b1", code: "B1", label: "店铺矩阵", sub: "平台门店数", x: 40, y: 200, w: 128, h: 68, color: c.navy, soft: "#e2e8f0", drillLevel: "platform" },
    { id: "b2", code: "B2", label: "品牌可见度", sub: "心智 / 搜索", x: 220, y: 60, w: 132, h: 68, color: c.teal, soft: "#d5efeb", drillLevel: "platform" },
    { id: "b3", code: "B3", label: "品牌销售额", sub: "多平台合计", x: 440, y: 60, w: 132, h: 68, color: c.green, soft: "#d9f0e2", drillLevel: "platform" },
    { id: "b4", code: "B4", label: "品牌利润池", sub: "扣费后贡献", x: 680, y: 160, w: 132, h: 68, color: c.gold, soft: "#f6e6d0" },
    { id: "b5", code: "B5", label: "品牌方信任", sub: "续约意愿", x: 440, y: 380, w: 132, h: 68, color: c.orange, soft: "#ffedd5" },
    { id: "b6", code: "B6", label: "品牌运营能力", sub: "策划/投放", x: 200, y: 280, w: 132, h: 68, color: c.purple, soft: "#ebe4ff" },
    { id: "b7", code: "B7", label: "库存与现金", sub: "品牌资源", x: 680, y: 340, w: 132, h: 68, color: c.rose, soft: "#f8dce3", drillLevel: "platform" },
  ],
  flows: [
    { id: "be1", from: "b1", to: "b2", polarity: "+", chains: ["G"], label: "覆盖", bend: -0.1 },
    { id: "be2", from: "b2", to: "b3", polarity: "+", chains: ["G"], label: "转化", bend: 0 },
    { id: "be3", from: "b3", to: "b4", polarity: "+", chains: ["G", "P"], label: "贡献", bend: 0.12 },
    { id: "be4", from: "b4", to: "b5", polarity: "+", chains: ["G"], label: "业绩信任", bend: 0.2 },
    { id: "be5", from: "b5", to: "b1", polarity: "+", chains: ["G"], label: "扩店/续约", bend: 0.25 },
    { id: "be6", from: "b6", to: "b3", polarity: "+", chains: ["O"], label: "运营拉动", bend: -0.15 },
    { id: "be7", from: "b7", to: "b6", polarity: "+", chains: ["O", "P"], label: "资源支撑", bend: -0.1 },
    { id: "be8", from: "b3", to: "b7", polarity: "-", delay: true, chains: ["P"], label: "消耗", bend: 0.18 },
    { id: "be9", from: "b4", to: "b7", polarity: "+", chains: ["P"], label: "反哺现金", bend: 0.08 },
  ],
  chains: [
    { id: "all", name: "全貌", color: "#64748b", desc: "品牌经营骨架" },
    { id: "G", name: "增长", color: "#ea580c", desc: "店铺→可见→销售→利润→信任→扩店" },
    { id: "O", name: "运营", color: "#7c3aed", desc: "资源→能力→销售" },
    { id: "P", name: "利润现金", color: "#be123c", desc: "销售耗资源 / 利润反哺" },
  ],
  loops: [
    { code: "R-B1", kind: "R", name: "品牌扩店飞轮", path: "B1→B2→B3→B4→B5→B1", chains: ["G"], edgeIds: ["be1", "be2", "be3", "be4", "be5"] },
    { code: "B-B1", kind: "B", name: "销资挤兑", path: "B3⊖//B7→B6→B3", chains: ["P"], edgeIds: ["be8", "be7", "be6"] },
  ],
};

const platform: LevelModel = {
  level: "platform",
  title: "平台层 · 多渠道汇总",
  subtitle: "同一电商平台下多渠道（店群）费用与流量结构汇总。",
  viewW: 960,
  viewH: 500,
  rollupHint: "上卷至品牌：平台销售额、流量、库存现金占用。",
  drillHint: "点击销售额 / 渠道费用 → 渠道层。",
  stocks: [
    { id: "p1", code: "P1", label: "渠道数量", sub: "店/账号数", x: 40, y: 200, w: 120, h: 64, color: c.navy, soft: "#e2e8f0", drillLevel: "channel" },
    { id: "p2", code: "P2", label: "平台流量", sub: "免费+付费", x: 220, y: 50, w: 120, h: 64, color: c.blue, soft: "#dbe7ff", drillLevel: "channel" },
    { id: "p3", code: "P3", label: "平台销售额", sub: "GMV 合计", x: 440, y: 50, w: 128, h: 64, color: c.green, soft: "#d9f0e2", drillLevel: "channel" },
    { id: "p4", code: "P4", label: "平台费用池", sub: "佣金/扣点/活动", x: 680, y: 120, w: 140, h: 64, color: c.orange, soft: "#ffedd5" },
    { id: "p5", code: "P5", label: "平台贡献利润", sub: "扣费后", x: 680, y: 280, w: 140, h: 64, color: c.gold, soft: "#f6e6d0" },
    { id: "p6", code: "P6", label: "库存现金占用", sub: "平台级", x: 220, y: 360, w: 140, h: 64, color: c.rose, soft: "#f8dce3", drillLevel: "channel" },
    { id: "p7", code: "P7", label: "体验分健康", sub: "处罚/限流", x: 440, y: 360, w: 128, h: 64, color: c.teal, soft: "#d5efeb" },
  ],
  flows: [
    { id: "pe1", from: "p1", to: "p2", polarity: "+", chains: ["G"], label: "覆盖", bend: -0.1 },
    { id: "pe2", from: "p2", to: "p3", polarity: "+", chains: ["G"], label: "转化", bend: 0 },
    { id: "pe3", from: "p3", to: "p4", polarity: "+", chains: ["C"], label: "费用随量", bend: 0.1 },
    { id: "pe4", from: "p3", to: "p5", polarity: "+", chains: ["G"], label: "收入", bend: 0.15 },
    { id: "pe5", from: "p4", to: "p5", polarity: "-", chains: ["C"], label: "侵蚀利润", bend: 0.05 },
    { id: "pe6", from: "p3", to: "p6", polarity: "-", delay: true, chains: ["R"], label: "占压", bend: 0.2 },
    { id: "pe7", from: "p6", to: "p3", polarity: "+", chains: ["R"], label: "供给支撑", bend: -0.18 },
    { id: "pe8", from: "p7", to: "p2", polarity: "+", chains: ["X"], label: "流量权重", bend: -0.12 },
    { id: "pe9", from: "p3", to: "p7", polarity: "+", chains: ["X"], label: "履约反馈", bend: 0.22 },
  ],
  chains: [
    { id: "all", name: "全貌", color: "#64748b", desc: "平台汇总骨架" },
    { id: "G", name: "增长", color: "#ea580c", desc: "渠道→流量→销售→利润" },
    { id: "C", name: "费用", color: "#ea580c", desc: "销量推高平台费用侵蚀利润" },
    { id: "R", name: "资源", color: "#be123c", desc: "销售占压库存现金" },
    { id: "X", name: "体验", color: "#0f766e", desc: "体验分影响流量" },
  ],
  loops: [
    { code: "R-P1", kind: "R", name: "平台增长飞轮", path: "P1→P2→P3→P5", chains: ["G"], edgeIds: ["pe1", "pe2", "pe4"] },
    { code: "B-P1", kind: "B", name: "费用刹车", path: "P3→P4⊖P5", chains: ["C"], edgeIds: ["pe3", "pe5"] },
  ],
};

const channel: LevelModel = {
  level: "channel",
  title: "渠道层 · 店群经营",
  subtitle: "多链接 + 保证金、库存、TP/交接金、代运营固定费与人工成本。",
  viewW: 1000,
  viewH: 540,
  rollupHint: "上卷至平台：销售额、费用、库存现金、体验。",
  drillHint: "点击销售额 / 链接贡献 → 链接层。",
  stocks: [
    { id: "c1", code: "C1", label: "链接矩阵", sub: "在售链接数", x: 36, y: 210, w: 120, h: 64, color: c.navy, soft: "#e2e8f0", drillLevel: "link" },
    { id: "c2", code: "C2", label: "渠道销售额", sub: "店 GMV", x: 220, y: 48, w: 124, h: 64, color: c.green, soft: "#d9f0e2", drillLevel: "link" },
    { id: "c3", code: "C3", label: "渠道毛利贡献", sub: "扣经营费用前", x: 420, y: 48, w: 132, h: 64, color: c.gold, soft: "#f6e6d0" },
    { id: "c4", code: "C4", label: "保证金", sub: "平台押金", x: 640, y: 48, w: 112, h: 64, color: c.slate, soft: "#e2e8f0" },
    { id: "c5", code: "C5", label: "库存", sub: "渠道仓", x: 800, y: 160, w: 112, h: 64, color: c.rose, soft: "#f8dce3" },
    { id: "c6", code: "C6", label: "TP/交接金", sub: "入驻/移交", x: 800, y: 300, w: 112, h: 64, color: "#0369a1", soft: "#d7eef8" },
    { id: "c7", code: "C7", label: "代运营固定费", sub: "月固定", x: 420, y: 380, w: 132, h: 64, color: c.orange, soft: "#ffedd5" },
    { id: "c8", code: "C8", label: "人工成本", sub: "工资/报销/技术费", x: 220, y: 380, w: 148, h: 64, color: c.purple, soft: "#ebe4ff", details: ["工资", "报销", "基础技术费", "加班/提成"] },
    { id: "c9", code: "C9", label: "推广分摊", sub: "渠道投放", x: 36, y: 48, w: 120, h: 64, color: c.blue, soft: "#dbe7ff", drillLevel: "link" },
    { id: "c10", code: "C10", label: "体验扣款", sub: "惩罚/赔付", x: 640, y: 380, w: 120, h: 64, color: "#b91c1c", soft: "#fee2e2" },
  ],
  flows: [
    { id: "ce1", from: "c1", to: "c2", polarity: "+", chains: ["G"], label: "供给页", bend: -0.12 },
    { id: "ce2", from: "c9", to: "c2", polarity: "+", chains: ["G"], label: "拉新", bend: 0 },
    { id: "ce3", from: "c2", to: "c3", polarity: "+", chains: ["G"], label: "贡献", bend: 0 },
    { id: "ce4", from: "c7", to: "c3", polarity: "-", chains: ["F"], label: "固定费", bend: 0.1 },
    { id: "ce5", from: "c8", to: "c3", polarity: "-", chains: ["F"], label: "人工", bend: 0.18 },
    { id: "ce6", from: "c10", to: "c3", polarity: "-", chains: ["F"], label: "扣款", bend: -0.08 },
    { id: "ce7", from: "c2", to: "c5", polarity: "-", delay: true, chains: ["R"], label: "出货占压", bend: 0.15 },
    { id: "ce8", from: "c5", to: "c2", polarity: "+", chains: ["R"], label: "有货可售", bend: -0.2 },
    { id: "ce9", from: "c4", to: "c2", polarity: "+", chains: ["R"], label: "准入", bend: 0.2 },
    { id: "ce10", from: "c6", to: "c1", polarity: "+", chains: ["R"], label: "资产沉淀", bend: -0.1 },
    { id: "ce11", from: "c9", to: "c3", polarity: "-", chains: ["F"], label: "推广成本", bend: 0.22 },
  ],
  chains: [
    { id: "all", name: "全貌", color: "#64748b", desc: "渠道经营骨架" },
    { id: "G", name: "销售", color: "#ea580c", desc: "链接/推广→销售→毛利贡献" },
    { id: "F", name: "费用", color: "#ea580c", desc: "固定费/人工/扣款/推广侵蚀贡献" },
    { id: "R", name: "资源", color: "#be123c", desc: "保证金·库存·交接金支撑经营" },
  ],
  loops: [
    { code: "R-C1", kind: "R", name: "链接增产飞轮", path: "C1→C2→C3", chains: ["G"], edgeIds: ["ce1", "ce3"] },
    { code: "B-C1", kind: "B", name: "费用挤压", path: "固定费/人工⊖贡献", chains: ["F"], edgeIds: ["ce4", "ce5", "ce6"] },
    { code: "B-C2", kind: "B", name: "库存挤兑", path: "C2⊖//C5→C2", chains: ["R"], edgeIds: ["ce7", "ce8"] },
  ],
};

const link: LevelModel = {
  level: "link",
  title: "链接层 · 多 SKU 组合页",
  subtitle: "商品详情页维度：SKU 汇总 + 页转化、连带、页级推广。",
  viewW: 960,
  viewH: 500,
  rollupHint: "上卷至渠道：链接 GMV、推广与转化质量。",
  drillHint: "点击任一 SKU 相关 Stock → SKU 层。",
  stocks: [
    { id: "l1", code: "L1", label: "SKU 组合", sub: "挂靠规格数", x: 40, y: 200, w: 120, h: 64, color: c.navy, soft: "#e2e8f0", drillLevel: "sku" },
    { id: "l2", code: "L2", label: "页曝光", sub: "UV / 曝光", x: 220, y: 48, w: 112, h: 64, color: c.blue, soft: "#dbe7ff" },
    { id: "l3", code: "L3", label: "转化率", sub: "下单转化", x: 400, y: 48, w: 112, h: 64, color: c.teal, soft: "#d5efeb" },
    { id: "l4", code: "L4", label: "链接销售额", sub: "页 GMV", x: 580, y: 48, w: 124, h: 64, color: c.green, soft: "#d9f0e2", drillLevel: "sku" },
    { id: "l5", code: "L5", label: "连带率", sub: "件/单", x: 780, y: 140, w: 112, h: 64, color: "#0369a1", soft: "#d7eef8" },
    { id: "l6", code: "L6", label: "页级推广", sub: "直通车等", x: 220, y: 360, w: 112, h: 64, color: c.orange, soft: "#ffedd5" },
    { id: "l7", code: "L7", label: "页贡献利润", sub: "汇总毛利", x: 580, y: 360, w: 124, h: 64, color: c.gold, soft: "#f6e6d0", drillLevel: "sku" },
    { id: "l8", code: "L8", label: "退款率", sub: "页退款", x: 400, y: 360, w: 112, h: 64, color: c.rose, soft: "#f8dce3", drillLevel: "sku" },
  ],
  flows: [
    { id: "le1", from: "l1", to: "l5", polarity: "+", chains: ["G"], label: "可选规格", bend: 0.1 },
    { id: "le2", from: "l2", to: "l3", polarity: "+", chains: ["G"], label: "流量质", bend: 0 },
    { id: "le3", from: "l3", to: "l4", polarity: "+", chains: ["G"], label: "成交", bend: 0 },
    { id: "le4", from: "l6", to: "l2", polarity: "+", chains: ["A"], label: "买流", bend: -0.12 },
    { id: "le5", from: "l5", to: "l4", polarity: "+", chains: ["G"], label: "提客单", bend: -0.1 },
    { id: "le6", from: "l4", to: "l7", polarity: "+", chains: ["G"], label: "贡献", bend: 0.2 },
    { id: "le7", from: "l8", to: "l7", polarity: "-", chains: ["B"], label: "侵蚀", bend: 0 },
    { id: "le8", from: "l6", to: "l7", polarity: "-", chains: ["A"], label: "投放成本", bend: 0.15 },
    { id: "le9", from: "l4", to: "l8", polarity: "+", delay: true, chains: ["B"], label: "基数↑退也↑", bend: 0.18 },
    { id: "le10", from: "l1", to: "l4", polarity: "+", chains: ["G"], label: "SKU 汇总", bend: -0.2 },
  ],
  chains: [
    { id: "all", name: "全貌", color: "#64748b", desc: "链接页骨架" },
    { id: "G", name: "成交", color: "#ea580c", desc: "曝光→转化→销售→利润" },
    { id: "A", name: "投放", color: "#2563eb", desc: "页推拉曝光也吃利润" },
    { id: "B", name: "退款", color: "#be123c", desc: "退款调节贡献" },
  ],
  loops: [
    { code: "R-L1", kind: "R", name: "页成交飞轮", path: "L2→L3→L4→L7", chains: ["G"], edgeIds: ["le2", "le3", "le6"] },
    { code: "B-L1", kind: "B", name: "投放挤利润", path: "L6→L2…⊖L7", chains: ["A"], edgeIds: ["le4", "le8"] },
  ],
};

const sku: LevelModel = {
  level: "sku",
  title: "SKU 层 · 单规格经济",
  subtitle: "平台费、销售额、退款、产品成本、物流、推广、仓储、利润等单品回路。",
  viewW: 1040,
  viewH: 560,
  rollupHint: "上卷至链接：各 SKU 销售、退款、毛利汇总。",
  drillHint: "已是最细层；点击节点可展开费用细项。",
  stocks: [
    { id: "k1", code: "K1", label: "价盘/件单价", sub: "定价", x: 40, y: 40, w: 120, h: 58, color: c.slate, soft: "#e2e8f0", details: ["挂牌价", "活动价", "折扣"] },
    { id: "k2", code: "K2", label: "销量", sub: "件数", x: 200, y: 40, w: 100, h: 58, color: c.blue, soft: "#dbe7ff" },
    { id: "k3", code: "K3", label: "销售额", sub: "GMV", x: 360, y: 40, w: 110, h: 58, color: c.green, soft: "#d9f0e2" },
    { id: "k4", code: "K4", label: "退款金额", sub: "退货退款", x: 520, y: 40, w: 110, h: 58, color: c.rose, soft: "#f8dce3", details: ["仅退款", "退货退款", "运费险"] },
    { id: "k5", code: "K5", label: "产品成本", sub: "采购/生产", x: 40, y: 200, w: 120, h: 58, color: "#92400e", soft: "#fef3c7" },
    { id: "k6", code: "K6", label: "平台费用", sub: "佣金/扣点", x: 200, y: 200, w: 120, h: 58, color: c.orange, soft: "#ffedd5", details: ["类目佣金", "类目扣点", "活动报名费"] },
    { id: "k7", code: "K7", label: "推广费", sub: "广告池", x: 360, y: 200, w: 110, h: 58, color: "#2563eb", soft: "#dbeafe", details: ["直通车", "万相台", "站外投放"] },
    { id: "k8", code: "K8", label: "物流成本", sub: "打包/运输/仓配", x: 520, y: 200, w: 140, h: 58, color: c.teal, soft: "#d5efeb", details: ["打包费", "运输费", "仓储运输费"] },
    { id: "k9", code: "K9", label: "仓储费用", sub: "仓租/操作", x: 700, y: 200, w: 120, h: 58, color: "#0e7490", soft: "#cffafe", details: ["仓租", "出入库操作费"] },
    { id: "k10", code: "K10", label: "售后成本", sub: "补发/客服", x: 680, y: 40, w: 120, h: 58, color: "#b91c1c", soft: "#fee2e2" },
    { id: "k11", code: "K11", label: "利润", sub: "单品贡献", x: 400, y: 400, w: 120, h: 64, color: c.gold, soft: "#f6e6d0" },
    { id: "k12", code: "K12", label: "推广 ROI", sub: "费效", x: 40, y: 360, w: 110, h: 58, color: c.purple, soft: "#ebe4ff" },
    { id: "k13", code: "K13", label: "库存周转", sub: "动销/缺货", x: 200, y: 360, w: 120, h: 58, color: c.rose, soft: "#f8dce3", details: ["周转天数", "缺货损失", "滞销减值"] },
    { id: "k14", code: "K14", label: "动销健康", sub: "可售天数", x: 700, y: 360, w: 120, h: 58, color: c.navy, soft: "#e2e8f0" },
  ],
  flows: [
    { id: "ke1", from: "k1", to: "k2", polarity: "-", chains: ["S"], label: "价↑量↓", bend: 0 },
    { id: "ke2", from: "k2", to: "k3", polarity: "+", chains: ["S"], label: "量×价", bend: 0 },
    { id: "ke3", from: "k1", to: "k3", polarity: "+", chains: ["S"], label: "客单", bend: -0.15 },
    { id: "ke4", from: "k3", to: "k4", polarity: "+", chains: ["R"], label: "基数", bend: 0 },
    { id: "ke5", from: "k3", to: "k11", polarity: "+", chains: ["P"], label: "收入", bend: 0.2 },
    { id: "ke6", from: "k4", to: "k11", polarity: "-", chains: ["R", "P"], label: "退款", bend: 0.1 },
    { id: "ke7", from: "k5", to: "k11", polarity: "-", chains: ["P"], label: "成本", bend: 0.25 },
    { id: "ke8", from: "k6", to: "k11", polarity: "-", chains: ["P"], label: "平台费", bend: 0.12 },
    { id: "ke9", from: "k7", to: "k11", polarity: "-", chains: ["A", "P"], label: "推广", bend: 0 },
    { id: "ke10", from: "k8", to: "k11", polarity: "-", chains: ["P"], label: "物流", bend: -0.08 },
    { id: "ke11", from: "k9", to: "k11", polarity: "-", chains: ["P"], label: "仓储", bend: -0.15 },
    { id: "ke12", from: "k10", to: "k11", polarity: "-", chains: ["R", "P"], label: "售后", bend: -0.05 },
    { id: "ke13", from: "k7", to: "k2", polarity: "+", chains: ["A"], label: "买量", bend: -0.18 },
    { id: "ke14", from: "k3", to: "k12", polarity: "+", chains: ["A"], label: "产出", bend: 0.22 },
    { id: "ke15", from: "k7", to: "k12", polarity: "-", chains: ["A"], label: "投入", bend: 0.15 },
    { id: "ke16", from: "k12", to: "k7", polarity: "+", chains: ["A"], label: "加投/减投", bend: 0.28 },
    { id: "ke17", from: "k13", to: "k2", polarity: "+", chains: ["I"], label: "有货", bend: -0.1 },
    { id: "ke18", from: "k2", to: "k13", polarity: "-", delay: true, chains: ["I"], label: "消耗库存", bend: 0.18 },
    { id: "ke19", from: "k13", to: "k14", polarity: "+", chains: ["I"], label: "周转", bend: 0.1 },
    { id: "ke20", from: "k14", to: "k11", polarity: "+", chains: ["I", "P"], label: "减少滞销", bend: -0.2 },
  ],
  chains: [
    { id: "all", name: "全貌", color: "#64748b", desc: "SKU 单品经济骨架" },
    { id: "S", name: "量价", color: "#15803d", desc: "价盘×销量→销售额" },
    { id: "P", name: "利润", color: "#B8863B", desc: "收入 − 退款/成本/平台/推广/物流/仓/售后" },
    { id: "A", name: "推广", color: "#2563eb", desc: "推广拉动销量与 ROI 反馈" },
    { id: "R", name: "退货", color: "#be123c", desc: "退款与售后侵蚀利润" },
    { id: "I", name: "库存", color: "#0f766e", desc: "周转/缺货调节销量与利润" },
  ],
  loops: [
    { code: "R-K1", kind: "R", name: "量价销售环", path: "K1·K2→K3→K11", chains: ["S"], edgeIds: ["ke2", "ke3", "ke5"] },
    { code: "B-K1", kind: "B", name: "费用挤压利润", path: "各项成本⊖K11", chains: ["P"], edgeIds: ["ke6", "ke7", "ke8", "ke9", "ke10", "ke11"] },
    { code: "R-K2", kind: "R", name: "推广 ROI 反馈", path: "K7→K2→K3→K12→K7", chains: ["A"], edgeIds: ["ke13", "ke2", "ke14", "ke16"] },
    { code: "B-K2", kind: "B", name: "库存挤兑", path: "K2⊖//K13→K2", chains: ["I"], edgeIds: ["ke18", "ke17"] },
  ],
};

export const LEVEL_MODELS: Record<LoopLevel, LevelModel> = {
  company,
  brand,
  platform,
  channel,
  link,
  sku,
};

export function getLevelModel(level: LoopLevel): LevelModel {
  return LEVEL_MODELS[level];
}
