# Generated by Django 5.2.16 on 2026-07-16 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWeComBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wecom_userid', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='企业微信 UserID')),
                ('normalized_phone_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='标准化手机号哈希')),
                ('status', models.CharField(choices=[('pending', '待匹配'), ('matched', '已绑定'), ('not_found', '未查询到成员'), ('invalid_phone', '手机号无效'), ('duplicate_phone', '手机号重复'), ('conflict', '绑定冲突'), ('permission_denied', '权限不足'), ('retry_waiting', '等待重试'), ('disabled', '已停用')], db_index=True, default='pending', max_length=32, verbose_name='绑定状态')),
                ('source', models.CharField(choices=[('user_created', '用户创建'), ('phone_updated', '手机号更新'), ('scheduled_sync', '定时同步'), ('manual', '立即匹配'), ('admin_confirmed', '管理员确认')], default='user_created', max_length=32, verbose_name='匹配来源')),
                ('failure_code', models.CharField(blank=True, default='', max_length=64, verbose_name='失败代码')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='失败原因')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='匹配时间')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='验证时间')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='重试次数')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下次重试时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_binding', to=settings.AUTH_USER_MODEL, verbose_name='平台用户')),
                ('wecom_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_bindings', to='wecom.wecomapiconfig', verbose_name='企业微信配置')),
            ],
            options={
                'verbose_name': '平台用户企业微信绑定',
                'verbose_name_plural': '平台用户企业微信绑定',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeComBindingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', '待匹配'), ('matched', '已绑定'), ('not_found', '未查询到成员'), ('invalid_phone', '手机号无效'), ('duplicate_phone', '手机号重复'), ('conflict', '绑定冲突'), ('permission_denied', '权限不足'), ('retry_waiting', '等待重试'), ('disabled', '已停用')], max_length=32)),
                ('message', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wecom_binding_actions', to=settings.AUTH_USER_MODEL)),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='wecom.userwecombinding')),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_binding_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeComBindingSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败')], db_index=True, default='pending', max_length=20, verbose_name='任务状态')),
                ('source', models.CharField(choices=[('user_created', '用户创建'), ('phone_updated', '手机号更新'), ('scheduled_sync', '定时同步'), ('manual', '立即匹配'), ('admin_confirmed', '管理员确认')], default='scheduled_sync', max_length=32, verbose_name='触发来源')),
                ('batch_size', models.PositiveSmallIntegerField(default=100, verbose_name='批大小')),
                ('scanned_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('not_found_count', models.PositiveIntegerField(default=0)),
                ('invalid_phone_count', models.PositiveIntegerField(default=0)),
                ('duplicate_phone_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('permission_denied_count', models.PositiveIntegerField(default=0)),
                ('retry_waiting_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wecom_binding_jobs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='binding_sync_jobs', to='wecom.wecomapiconfig', verbose_name='企业微信配置')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
