# Generated by Django 5.2.16 on 2026-07-16 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0004_generate_system_callback_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeComGroupWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='群聊名称')),
                ('webhook_key_encrypted', models.TextField(verbose_name='群机器人 Webhook Key（密文）')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_group_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeComNotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('person', '应用消息'), ('group', '群机器人')], max_length=16)),
                ('target_ids', models.JSONField(default=list)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('content_preview', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('accepted', '企业微信已受理'), ('partial', '部分接收人失败'), ('failed', '发送失败')], db_index=True, default='failed', max_length=16)),
                ('wecom_msgid', models.CharField(blank=True, default='', max_length=128)),
                ('invalid_users', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_reason', models.CharField(blank=True, default='', max_length=500)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='wecom.wecomapiconfig')),
                ('group_webhook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_records', to='wecom.wecomgroupwebhook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_notification_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='wecomgroupwebhook',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_wecom_group_name_per_user'),
        ),
    ]
