# Generated by Django 5.2.16 on 2026-07-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0005_wecomgroupwebhook_wecomnotificationrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wecomcallbackevent',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wecomcallbackevent',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wecomcallbackevent',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='wecomcallbackevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wecomcallbackevent',
            name='processing_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wecomcallbackevent',
            name='processing_status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('retry_waiting', '等待重试'), ('failed', '处理失败')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='wecomgroupwebhook',
            name='last_error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='wecomgroupwebhook',
            name='last_error_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wecomgroupwebhook',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wecomgroupwebhook',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wecomnotificationrecord',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wecomnotificationrecord',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wecomnotificationrecord',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wecomnotificationrecord',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='wecomnotificationrecord',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='wecomnotificationrecord',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wecomnotificationrecord',
            name='task_trace_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='wecomnotificationrecord',
            name='status',
            field=models.CharField(choices=[('pending', '等待发送'), ('retry_waiting', '等待重试'), ('accepted', '企业微信已受理'), ('partial', '部分接收人失败'), ('failed', '发送失败')], db_index=True, default='failed', max_length=16),
        ),
    ]
