# Generated by Django 5.2.16 on 2026-07-16 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0006_wecomcallbackevent_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wecomapiconfig',
            name='contacts_sync_error',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='通讯录同步错误'),
        ),
        migrations.AddField(
            model_name='wecomapiconfig',
            name='contacts_synced_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='通讯录同步时间'),
        ),
        migrations.CreateModel(
            name='WeComContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wecom_userid', models.CharField(max_length=128, verbose_name='企业微信 UserID')),
                ('name', models.CharField(max_length=128, verbose_name='成员姓名')),
                ('department', models.CharField(blank=True, default='', max_length=500, verbose_name='部门')),
                ('department_ids', models.JSONField(blank=True, default=list, verbose_name='部门 ID')),
                ('position', models.CharField(blank=True, default='', max_length=128, verbose_name='职务')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='头像地址')),
                ('available', models.BooleanField(db_index=True, default=True, verbose_name='成员可用')),
                ('synced_at', models.DateTimeField(db_index=True, verbose_name='同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='wecom.wecomapiconfig', verbose_name='企业微信配置')),
            ],
            options={
                'ordering': ['department', 'name', 'id'],
                'indexes': [models.Index(fields=['config', 'available'], name='wecom_contact_cfg_available')],
                'constraints': [models.UniqueConstraint(fields=('config', 'wecom_userid'), name='uniq_wecom_contact_config_userid')],
            },
        ),
    ]
