# Generated by Django 5.2.16 on 2026-07-16 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organization_organizationmembership'),
        ('wecom', '0007_wecomapiconfig_contacts_sync_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wecomgroupwebhook',
            name='uniq_wecom_group_name_per_user',
        ),
        migrations.AddField(
            model_name='wecomapiconfig',
            name='access_scope',
            field=models.CharField(choices=[('organization', '企业全员'), ('selected', '指定成员'), ('owner', '仅配置者')], db_index=True, default='organization', max_length=20, verbose_name='可用范围'),
        ),
        migrations.AddField(
            model_name='wecomapiconfig',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_wecom_api_configs', to=settings.AUTH_USER_MODEL, verbose_name='指定可用成员'),
        ),
        migrations.AddField(
            model_name='wecomapiconfig',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='wecomapiconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wecom_api_configs', to='core.organization', verbose_name='所属企业'),
        ),
        migrations.AddField(
            model_name='wecomgroupwebhook',
            name='access_scope',
            field=models.CharField(choices=[('organization', '企业全员'), ('selected', '指定成员'), ('owner', '仅配置者')], db_index=True, default='organization', max_length=20),
        ),
        migrations.AddField(
            model_name='wecomgroupwebhook',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_wecom_group_webhooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wecomgroupwebhook',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wecom_group_webhooks', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='userwecombinding',
            name='wecom_userid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='企业微信 UserID'),
        ),
        migrations.AddConstraint(
            model_name='userwecombinding',
            constraint=models.UniqueConstraint(condition=models.Q(('wecom_config__isnull', False), ('wecom_userid__isnull', False)), fields=('wecom_config', 'wecom_userid'), name='uniq_wecom_userid_per_config'),
        ),
        migrations.AddConstraint(
            model_name='wecomgroupwebhook',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_wecom_group_name_per_org'),
        ),
    ]
