# Generated by Django 5.2.16 on 2026-07-17 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wecom', '0010_wecomcliconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wecomcliconfig',
            name='access_scope',
            field=models.CharField(choices=[('organization', '企业全员'), ('selected', '指定成员'), ('owner', '仅管理员')], db_index=True, default='organization', max_length=20),
        ),
        migrations.AddField(
            model_name='wecomcliconfig',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_wecom_cli_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
