# Generated by Django 5.2.16 on 2026-07-20 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_platform_team_creator_membership'),
        ('wecom', '0012_alter_wecomcliconfig_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wecomapiconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wecom_api_configs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddConstraint(
            model_name='wecomapiconfig',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='uniq_wecom_api_config_per_user_org'),
        ),
    ]
